

services:
  codrr_pg:
    image: postgres:16.3
    container_name: codrr_pg
    restart: always
    environment:
      POSTGRES_DB: codrrdb
      POSTGRES_USER: ucodrr
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432